Update badpro

diff --git a/Modulos/badpro b/Modulos/badpro
--- a/Modulos/badpro
+++ b/Modulos/badpro
@@ -1,18 +1,18 @@
 #!/bin/bash
 fun_badvpn() {
-    clear
-    echo -e "\E[44;1;37m            INSTALAÇÃO BADVPN PRO            \E[0m"
-    echo ""
+	echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
+	echo -e "\033[0;34m┃\E[44;1;37m         GERENCIAR BADVPN PRO             \E[0m\033[0;34m┃"
+	echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
     if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
         echo -e "\033[1;33mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'badvpn-ud' | awk {'print $4'} | cut -d: -f2 | xargs)"
     else
         sleep 0.1
     fi
-    var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
+    var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m♦ " || echo -e "\033[1;31m○ ")
     echo ""
-    echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mATIVAR BADVPN (PRO) $var_sks1 \033[0m"
-    echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
-    echo -e "\033[1;31m\033[1;36m\033[1;31m \033[1;37m \033[1;33m\033[0m"
+    echo -e "\E[38;5;196m|\E[38;5;33m01\E[38;5;196m|\033[1;37m➜ \033[1;33mATIVAR BADVPN (PRO) $var_sks1 \033[0m"
+    echo -e "\E[38;5;196m|\E[38;5;33m02\E[38;5;196m|\033[1;37m➜ \033[1;33mABRIR PORTA\033[0m"
+    echo -e "\E[38;5;196m|\E[38;5;33m00\E[38;5;196m|\033[1;37m➜ \033[1;33mVOLTAR\033[0m"
     echo ""
     echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "
     read resposta
@@ -57,7 +57,7 @@ fun_badvpn() {
                     sleep 0.1
                 } || {
                     cd $HOME
-                    wget https://www.dropbox.com/s/48b36clnxkkurlz/badvpn-udpgw -o /dev/null
+                    wget wget https://github.com/PhoenixxZ2023/PLUS/main/Install/badvpn-udpgw -o /dev/null
                     mv -f $HOME/badvpn-udpgw /bin/badvpn-udpgw
                     chmod 777 /bin/badvpn-udpgw
                 }
@@ -103,11 +103,43 @@ fun_badvpn() {
             sleep 2
             fun_badvpn
         fi
+    elif [[ "$resposta" = '2' ]]; then
+        if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
+            tput reset
+	echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
+	echo -e "\033[0;34m┃\E[44;1;37m            GERENCIAR BADVPN             \E[0m\033[0;34m┃"
+	echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m\n"
+            echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
+            read porta
+            [[ -z "$porta" ]] && {
+                echo ""
+                echo -e "\033[1;31mPorta invalida!"
+                sleep 0.5
+                tput reset
+                fun_badvpn
+            }
+            fun_abrirptbad() {
+                screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:$porta --max-clients 10000 --max-connections-for-client 8
+                sleep 1
+            }
+			echo ""
+            echo -e "\033[1;32mINICIANDO O BADVPN NA PORTA \033[1;31m$porta\033[1;33m\n"
+			sleep 0.5
+			echo -e "\033[1;32mPORTA \033[1;31m$porta\033[1;32m ATIVADO COM SUCESSO\033[1;33m"
+            fun_abrirptbad
+			tput reset
+            sleep 0.5
+            fun_badvpn
+			else
+            echo -e "\033[1;31mFUNCAO INDISPONIVEL\n\n\033[1;33mATIVE O BADVPN PRIMEIRO !\033[1;33m"
+            sleep 0.5
+            fun_badvpn
+        fi
     elif [[ "$resposta" = '0' ]]; then
         echo ""
         echo -e "\033[1;31mRetornando...\033[0m"
         sleep 1
-        badpro1
+        menu
     else
         echo ""
         echo -e "\033[1;31mOpcao invalida !\033[0m"
@@ -115,4 +147,5 @@ fun_badvpn() {
         fun_badvpn
     fi
 }
+tput reset
 fun_badvpn
